# Generated by Django 4.2.7 on 2023-12-01 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('age', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='prof_pic')),
                ('gender', models.CharField(choices=[('', 'Select a gender'), ('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='', max_length=10)),
                ('religion', models.CharField(choices=[('', 'Select a Religion'), ('Muslim', 'Muslim'), ('Hindu', 'Hindu'), ('Buddist', 'Buddist')], default='', max_length=10)),
                ('address', models.TextField(max_length=100)),
            ],
        ),
    ]
