# Generated by Django 4.2.7 on 2023-12-02 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentProfileApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='religion',
            field=models.CharField(choices=[('', 'Select a Religion'), ('Islam', 'Islam'), ('Hindu', 'Hindu'), ('Buddist', 'Buddist')], default='', max_length=10),
        ),
    ]
