# Generated by Django 4.2.5 on 2023-12-03 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentProfileApp', '0002_alter_profile_religion'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='department',
            field=models.CharField(choices=[('', 'Select a Department'), ('CSE', 'CSE'), ('Civil', 'Civil'), ('EEE', 'EEE'), ('ME', 'ME'), ('Chemistry', 'Chemistry')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='su_id',
            field=models.CharField(default='CSE', max_length=20),
            preserve_default=False,
        ),
    ]
